### SHREYAN'S AI SKOOL

In [81]:
import pandas as pd
import numpy as np

In [82]:
data = {
    'state': ['Ohio', 'Ohio', 'Ohio', 'Nevada', 'Nevada'],
        'year': [2000, 2001, 2002, 2001, 2002],
        'pop': [1.5, 1.7, 3.6, 2.4, 2.9]
}
data = pd.DataFrame(data) 
data

    state  year  pop
0    Ohio  2000  1.5
1    Ohio  2001  1.7
2    Ohio  2002  3.6
3  Nevada  2001  2.4
4  Nevada  2002  2.9

### SELECTION AND INDEXING OF COLUMNS

In [83]:
data['state']

0      Ohio
1      Ohio
2      Ohio
3    Nevada
4    Nevada
Name: state, dtype: str

In [84]:
data[['state','year']]

    state  year
0    Ohio  2000
1    Ohio  2001
2    Ohio  2002
3  Nevada  2001
4  Nevada  2002

### CREATING A NEW COLUMN

In [85]:
data['designation'] = ['doctor','engineer','police','IAS','athlete']

In [86]:
data

    state  year  pop designation
0    Ohio  2000  1.5      doctor
1    Ohio  2001  1.7    engineer
2    Ohio  2002  3.6      police
3  Nevada  2001  2.4         IAS
4  Nevada  2002  2.9     athlete

### REMOVING A COLUMN

In [87]:
data.drop('designation',axis=1) 
# axis = 1 -> vertical like 1 need to mention to remove a column.

    state  year  pop
0    Ohio  2000  1.5
1    Ohio  2001  1.7
2    Ohio  2002  3.6
3  Nevada  2001  2.4
4  Nevada  2002  2.9

In [88]:
data

    state  year  pop designation
0    Ohio  2000  1.5      doctor
1    Ohio  2001  1.7    engineer
2    Ohio  2002  3.6      police
3  Nevada  2001  2.4         IAS
4  Nevada  2002  2.9     athlete

> only the copy me changes has been occured not in the actual DataFrame.

In [89]:
data.drop('designation',inplace=True, axis=1)

In [90]:
data

    state  year  pop
0    Ohio  2000  1.5
1    Ohio  2001  1.7
2    Ohio  2002  3.6
3  Nevada  2001  2.4
4  Nevada  2002  2.9

In [91]:
data.drop(['state','year'],axis=1)

   pop
0  1.5
1  1.7
2  3.6
3  2.4
4  2.9

In [92]:
data

    state  year  pop
0    Ohio  2000  1.5
1    Ohio  2001  1.7
2    Ohio  2002  3.6
3  Nevada  2001  2.4
4  Nevada  2002  2.9

### SELECTING ROWS

In [93]:
data

    state  year  pop
0    Ohio  2000  1.5
1    Ohio  2001  1.7
2    Ohio  2002  3.6
3  Nevada  2001  2.4
4  Nevada  2002  2.9

In [94]:
data.loc[0]

state    Ohio
year     2000
pop       1.5
Name: 0, dtype: object

In [95]:
data.loc[[0,1]]

  state  year  pop
0  Ohio  2000  1.5
1  Ohio  2001  1.7

In [96]:
data.iloc[3]

state    Nevada
year       2001
pop         2.4
Name: 3, dtype: object

### SELECTING SUBSETS OF ROWS AND COLUMNS

In [97]:
data

    state  year  pop
0    Ohio  2000  1.5
1    Ohio  2001  1.7
2    Ohio  2002  3.6
3  Nevada  2001  2.4
4  Nevada  2002  2.9

In [98]:
data.loc[[0,1]][['year','pop']]

   year  pop
0  2000  1.5
1  2001  1.7

In [99]:
data.loc[[2,3,4]][['state','year']]

    state  year
2    Ohio  2002
3  Nevada  2001
4  Nevada  2002

### CONDITIONAL SELECTION

In [100]:
data

    state  year  pop
0    Ohio  2000  1.5
1    Ohio  2001  1.7
2    Ohio  2002  3.6
3  Nevada  2001  2.4
4  Nevada  2002  2.9

> I only want to see those state whose pop is above 2.5

In [101]:
data[data['pop']>2.5]

    state  year  pop
2    Ohio  2002  3.6
4  Nevada  2002  2.9

> I only want states whose pop is above 1.5 and their year must be 2002

In [102]:
data[(data['pop']>1.5) & (data['year']==2002)]

    state  year  pop
2    Ohio  2002  3.6
4  Nevada  2002  2.9

# MISSING DATA

In [103]:
import  numpy as np
import pandas as pd

### FINDING MISSING DATA

In [104]:
# nan = not a number.
data = {
    'A': [1, 2, np.nan, 4, 5],
    'B': [1, 2, 3, 4, 5],
    'C': [1, 2, 3, np.nan, np.nan],
    'D': [1, np.nan, np.nan, np.nan, 5]
}
df = pd.DataFrame(data)

In [105]:
df

     A  B    C    D
0  1.0  1  1.0  1.0
1  2.0  2  2.0  NaN
2  NaN  3  3.0  NaN
3  4.0  4  NaN  NaN
4  5.0  5  NaN  5.0

> check for nan value with .isna() function.

In [106]:
df.isna()

       A      B      C      D
0  False  False  False  False
1  False  False  False   True
2   True  False  False   True
3  False  False   True   True
4  False  False   True  False

In [107]:
df.isna().sum()

A    1
B    0
C    2
D    3
dtype: int64

> any missing value in each column

In [108]:
df.isna().any()

A     True
B    False
C     True
D     True
dtype: bool

### REMOVING MISSING DATA

In [109]:
df

     A  B    C    D
0  1.0  1  1.0  1.0
1  2.0  2  2.0  NaN
2  NaN  3  3.0  NaN
3  4.0  4  NaN  NaN
4  5.0  5  NaN  5.0

> removes rows that contains null values.

In [110]:
df.dropna()

     A  B    C    D
0  1.0  1  1.0  1.0

In [111]:
df

     A  B    C    D
0  1.0  1  1.0  1.0
1  2.0  2  2.0  NaN
2  NaN  3  3.0  NaN
3  4.0  4  NaN  NaN
4  5.0  5  NaN  5.0

In [113]:
df.dropna(thresh=3) 
# atleast 3 non null values honi chaiye if  not then the whole row would be removed

     A  B    C    D
0  1.0  1  1.0  1.0
1  2.0  2  2.0  NaN
4  5.0  5  NaN  5.0

### FILLING THE MISSING DATA

In [ ]:
df.fillna(0)
# THIS IS COLUMN WISE.

     A  B    C    D
0  1.0  1  1.0  1.0
1  2.0  2  2.0  0.0
2  0.0  3  3.0  0.0
3  4.0  4  0.0  0.0
4  5.0  5  0.0  5.0

In [116]:
df 
# write inplace=True to see the actual effect.

     A  B    C    D
0  1.0  1  1.0  1.0
1  2.0  2  2.0  NaN
2  NaN  3  3.0  NaN
3  4.0  4  NaN  NaN
4  5.0  5  NaN  5.0

In [121]:
values = {'A':0,'B':100,'C':300,'D':400}
df.fillna(value=values)
# COLUMN WISE!

     A  B      C      D
0  1.0  1    1.0    1.0
1  2.0  2    2.0  400.0
2  0.0  3    3.0  400.0
3  4.0  4  300.0  400.0
4  5.0  5  300.0    5.0

In [122]:
df

     A  B    C    D
0  1.0  1  1.0  1.0
1  2.0  2  2.0  NaN
2  NaN  3  3.0  NaN
3  4.0  4  NaN  NaN
4  5.0  5  NaN  5.0

In [124]:
df.fillna(df.mean())

     A  B    C    D
0  1.0  1  1.0  1.0
1  2.0  2  2.0  3.0
2  3.0  3  3.0  3.0
3  4.0  4  2.0  3.0
4  5.0  5  2.0  5.0

# MERGING, JOINING & CONCATENATION

### MERGING 2 DF's

In [126]:
employees = pd.DataFrame({
    'employee_id': [1, 2, 3, 4, 5],
    'name': ['John', 'Anna', 'Peter', 'Linda', 'Bob'],
    'department': ['HR', 'IT', 'Finance', 'IT', 'HR']
})

# DataFrame 2: Salary information
salaries = pd.DataFrame({
    'employee_id': [1, 2, 3, 6, 7],
    'salary': [60000, 80000, 65000, 70000, 90000],
    'bonus': [5000, 10000, 7000, 8000, 12000]
})

In [127]:
employees

   employee_id   name department
0            1   John         HR
1            2   Anna         IT
2            3  Peter    Finance
3            4  Linda         IT
4            5    Bob         HR

In [128]:
salaries

   employee_id  salary  bonus
0            1   60000   5000
1            2   80000  10000
2            3   65000   7000
3            6   70000   8000
4            7   90000  12000

In [129]:
pd.merge(employees,salaries)

   employee_id   name department  salary  bonus
0            1   John         HR   60000   5000
1            2   Anna         IT   80000  10000
2            3  Peter    Finance   65000   7000

In [ ]:
pd.merge(employees,salaries, on='employee_id') 
# on means common between both uske basis pr merge.

   employee_id   name department  salary  bonus
0            1   John         HR   60000   5000
1            2   Anna         IT   80000  10000
2            3  Peter    Finance   65000   7000

In [136]:
pd.merge(employees,salaries, on='employee_id',how='inner')
# andar side me emp_id hai uske side pe merge.
# usually we use this.

   employee_id   name department  salary  bonus
0            1   John         HR   60000   5000
1            2   Anna         IT   80000  10000
2            3  Peter    Finance   65000   7000

In [137]:
pd.merge(employees,salaries, on='employee_id',how='outer')

   employee_id   name department   salary    bonus
0            1   John         HR  60000.0   5000.0
1            2   Anna         IT  80000.0  10000.0
2            3  Peter    Finance  65000.0   7000.0
3            4  Linda         IT      NaN      NaN
4            5    Bob         HR      NaN      NaN
5            6    NaN        NaN  70000.0   8000.0
6            7    NaN        NaN  90000.0  12000.0

In [138]:
pd.merge(employees,salaries, on='employee_id',how='left')
# merge on the basis of left i.e employees.

   employee_id   name department   salary    bonus
0            1   John         HR  60000.0   5000.0
1            2   Anna         IT  80000.0  10000.0
2            3  Peter    Finance  65000.0   7000.0
3            4  Linda         IT      NaN      NaN
4            5    Bob         HR      NaN      NaN

In [139]:
pd.merge(employees,salaries, on='employee_id',how='right')
# based on salaries

   employee_id   name department  salary  bonus
0            1   John         HR   60000   5000
1            2   Anna         IT   80000  10000
2            3  Peter    Finance   65000   7000
3            6    NaN        NaN   70000   8000
4            7    NaN        NaN   90000  12000

### CONCATENATION OF 2 DF's

In [140]:
df1 = pd.DataFrame({
    'A': ['A0', 'A1', 'A2'],
    'B': ['B0', 'B1', 'B2'],
    'C': ['C0', 'C1', 'C2']
})

df2 = pd.DataFrame({
    'A': ['A3', 'A4', 'A5'],
    'B': ['B3', 'B4', 'B5'],
    'C': ['C3', 'C4', 'C5']
})

In [141]:
df1

    A   B   C
0  A0  B0  C0
1  A1  B1  C1
2  A2  B2  C2

In [142]:
df2

    A   B   C
0  A3  B3  C3
1  A4  B4  C4
2  A5  B5  C5

In [145]:
pd.concat(df1,df2)

TypeError: concat() takes 1 positional argument but 2 were given

In [146]:
pd.concat([df1,df2])

    A   B   C
0  A0  B0  C0
1  A1  B1  C1
2  A2  B2  C2
0  A3  B3  C3
1  A4  B4  C4
2  A5  B5  C5

In [ ]:
pd.concat([df2,df1])
# based on columns

    A   B   C
0  A3  B3  C3
1  A4  B4  C4
2  A5  B5  C5
0  A0  B0  C0
1  A1  B1  C1
2  A2  B2  C2

In [149]:
pd.concat([df1,df2], axis=1) 
# done on the basis of rows.

    A   B   C   A   B   C
0  A0  B0  C0  A3  B3  C3
1  A1  B1  C1  A4  B4  C4
2  A2  B2  C2  A5  B5  C5

### JOINING 2 DATAFRAMES

In [150]:
df1 = pd.DataFrame({
    'name':['Alice','Bob','Charlie']
},index = [1,2,3])

df2 = pd.DataFrame({
    'score':[85,90,75]
},index=[2,3,4])

In [151]:
df1

      name
1    Alice
2      Bob
3  Charlie

In [152]:
df2

   score
2     85
3     90
4     75

> We have two series that we want to join.

In [154]:
df1.join(df2)
# inner join

      name  score
1    Alice    NaN
2      Bob   85.0
3  Charlie   90.0

In [155]:
df1.join(df2,how='outer')

      name  score
1    Alice    NaN
2      Bob   85.0
3  Charlie   90.0
4      NaN   75.0

In [156]:
df2.join(df1)

   score     name
2     85      Bob
3     90  Charlie
4     75      NaN

# GROUPBY & AGGREGATION

In [4]:
data = {
    'Category': ['A', 'B', 'A', 'B', 'A', 'B', 'A', 'B'],
    'Store': ['S1', 'S1', 'S2', 'S2', 'S1', 'S2', 'S2', 'S1'],
    'Sales': [100, 200, 150, 250, 120, 180, 200, 300],
    'Quantity': [10, 15, 12, 18, 8, 20, 15, 25],
    'Date': pd.date_range('2023-01-01', periods=8)
}

df = pd.DataFrame(data)
df

  Category Store  Sales  Quantity       Date
0        A    S1    100        10 2023-01-01
1        B    S1    200        15 2023-01-02
2        A    S2    150        12 2023-01-03
3        B    S2    250        18 2023-01-04
4        A    S1    120         8 2023-01-05
5        B    S2    180        20 2023-01-06
6        A    S2    200        15 2023-01-07
7        B    S1    300        25 2023-01-08

> category and store are categorical variable.

> Groupby category and calculate the sum of Sales.

In [10]:
df.groupby('Category')['Sales'].sum()

Category
A    570
B    930
Name: Sales, dtype: int64

>  Group by Store & calculate the sum of Sales.

In [11]:
df.groupby('Store')['Sales'].sum()

Store
S1    720
S2    780
Name: Sales, dtype: int64

> Group by multiple columns.

In [12]:
df.groupby(['Category','Store'])['Sales'].sum()

Category  Store
A         S1       220
          S2       350
B         S1       500
          S2       430
Name: Sales, dtype: int64

### AGGREGATION

It mean we want to combine the values and find something ex mean.

In [13]:
df

  Category Store  Sales  Quantity       Date
0        A    S1    100        10 2023-01-01
1        B    S1    200        15 2023-01-02
2        A    S2    150        12 2023-01-03
3        B    S2    250        18 2023-01-04
4        A    S1    120         8 2023-01-05
5        B    S2    180        20 2023-01-06
6        A    S2    200        15 2023-01-07
7        B    S1    300        25 2023-01-08

In [16]:
df['Sales'].mean()
"""
mean, median, mode, min, max, count, std
"""

'\nmean, median, mode, min, max, count, std\n'

In [21]:
df['Sales'].agg(['mean','min','max','std'])
# problem in mode.

mean    187.500000
min     100.000000
max     300.000000
std      66.062741
Name: Sales, dtype: float64

# PIVOT TABLES