## PHASE 2 OF LEARNING PANDAS

In [84]:
import numpy as np
import pandas as pd

In [85]:
dict1 = {
    "name" : ['harry','rohan','skillf','shubh'],
    "marks" : [93,34,24,17],
    "city" : ['rampur','kolkata','bareilly','antarctica']

}

df = pd.DataFrame(dict1)
print(df)

     name  marks        city
0   harry     93      rampur
1   rohan     34     kolkata
2  skillf     24    bareilly
3   shubh     17  antarctica

#### Transform the dictionary to the csv file.

In [86]:
df.to_csv('friends.csv')

#### Remove the index

In [87]:
df.to_csv('friends_index_false.csv', index = False)

In [88]:
df.head(2)

    name  marks     city
0  harry     93   rampur
1  rohan     34  kolkata

In [89]:
df.tail(2)

     name  marks        city
2  skillf     24    bareilly
3   shubh     17  antarctica

#### Calculate the satistical analysis of numerical column

In [90]:
df.describe()

           marks
count   4.000000
mean   42.000000
std    34.708308
min    17.000000
25%    22.250000
50%    29.000000
75%    48.750000
max    93.000000

#### Change the index

In [91]:
df.index = ['first','second','third','fourth']
df

          name  marks        city
first    harry     93      rampur
second   rohan     34     kolkata
third   skillf     24    bareilly
fourth   shubh     17  antarctica

#### Pandas DataStructure

In [92]:
ser = pd.Series(np.random.rand(34)) 
type(ser)

pandas.Series

In [93]:
newdf = pd.DataFrame(np.random.rand(334,5), index = np.arange(334))
newdf

            0         1         2         3         4
0    0.943622  0.015417  0.697285  0.904292  0.734435
1    0.228106  0.891075  0.052226  0.730936  0.859185
2    0.888869  0.508395  0.946337  0.582474  0.790120
3    0.787363  0.587360  0.730951  0.966586  0.603033
4    0.662317  0.504583  0.087809  0.308296  0.034064
..        ...       ...       ...       ...       ...
329  0.942308  0.953576  0.996571  0.518972  0.473479
330  0.244896  0.139392  0.856969  0.287743  0.438733
331  0.902689  0.637977  0.503709  0.264863  0.933552
332  0.571889  0.188152  0.930040  0.352570  0.673688
333  0.598487  0.365627  0.556993  0.077678  0.998507

[334 rows x 5 columns]

In [94]:
type(newdf)
newdf.head()

          0         1         2         3         4
0  0.943622  0.015417  0.697285  0.904292  0.734435
1  0.228106  0.891075  0.052226  0.730936  0.859185
2  0.888869  0.508395  0.946337  0.582474  0.790120
3  0.787363  0.587360  0.730951  0.966586  0.603033
4  0.662317  0.504583  0.087809  0.308296  0.034064

In [95]:
newdf.describe()

                0           1           2           3           4
count  334.000000  334.000000  334.000000  334.000000  334.000000
mean     0.492155    0.482684    0.516711    0.503239    0.491097
std      0.297331    0.284524    0.284720    0.293664    0.296674
min      0.005261    0.001299    0.004796    0.006170    0.000444
25%      0.227685    0.225459    0.299560    0.261868    0.240567
50%      0.465236    0.484888    0.539233    0.519484    0.499114
75%      0.763443    0.734226    0.750041    0.733084    0.734320
max      0.990408    0.989302    0.997724    0.998022    0.998507

In [96]:
newdf.dtypes

0    float64
1    float64
2    float64
3    float64
4    float64
dtype: object

In [97]:
print(newdf.index)
print("\n")
print(newdf.columns)

Index([  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,
       ...
       324, 325, 326, 327, 328, 329, 330, 331, 332, 333],
      dtype='int64', length=334)


RangeIndex(start=0, stop=5, step=1)

#### Convert my DataFrame to Numpy array

In [98]:
newdf.to_numpy

<bound method DataFrame.to_numpy of             0         1         2         3         4
0    0.943622  0.015417  0.697285  0.904292  0.734435
1    0.228106  0.891075  0.052226  0.730936  0.859185
2    0.888869  0.508395  0.946337  0.582474  0.790120
3    0.787363  0.587360  0.730951  0.966586  0.603033
4    0.662317  0.504583  0.087809  0.308296  0.034064
..        ...       ...       ...       ...       ...
329  0.942308  0.953576  0.996571  0.518972  0.473479
330  0.244896  0.139392  0.856969  0.287743  0.438733
331  0.902689  0.637977  0.503709  0.264863  0.933552
332  0.571889  0.188152  0.930040  0.352570  0.673688
333  0.598487  0.365627  0.556993  0.077678  0.998507

[334 rows x 5 columns]>

In [99]:
newdf.head()

          0         1         2         3         4
0  0.943622  0.015417  0.697285  0.904292  0.734435
1  0.228106  0.891075  0.052226  0.730936  0.859185
2  0.888869  0.508395  0.946337  0.582474  0.790120
3  0.787363  0.587360  0.730951  0.966586  0.603033
4  0.662317  0.504583  0.087809  0.308296  0.034064

#### Learn some attributes

In [100]:
# TRANSPOSE
newdf.T

,0,1,2,3,4,5,6,7,8,9,...,324,325,326,327,328,329,330,331,332,333
0,0.943622,0.228106,0.888869,0.787363,0.662317,0.806023,0.951344,0.640022,0.834838,0.791262,...,0.728594,0.794590,0.550169,0.720793,0.179568,0.942308,0.244896,0.902689,0.571889,0.598487
1,0.015417,0.891075,0.508395,0.587360,0.504583,0.704941,0.660100,0.655816,0.330902,0.039764,...,0.159591,0.541483,0.790760,0.763472,0.122733,0.953576,0.139392,0.637977,0.188152,0.365627
2,0.697285,0.052226,0.946337,0.730951,0.087809,0.335382,0.657673,0.156829,0.798682,0.969652,...,0.826268,0.413445,0.594174,0.301553,0.389155,0.996571,0.856969,0.503709,0.930040,0.556993
3,0.904292,0.730936,0.582474,0.966586,0.308296,0.264778,0.154159,0.496781,0.489880,0.450600,...,0.338766,0.109754,0.587591,0.355274,0.277006,0.518972,0.287743,0.264863,0.352570,0.077678
4,0.734435,0.859185,0.790120,0.603033,0.034064,0.873578,0.192244,0.315044,0.243152,0.066347,...,0.166512,0.989286,0.508279,0.779378,0.731407,0.473479,0.438733,0.933552,0.673688,0.998507

In [101]:
newdf.head()

          0         1         2         3         4
0  0.943622  0.015417  0.697285  0.904292  0.734435
1  0.228106  0.891075  0.052226  0.730936  0.859185
2  0.888869  0.508395  0.946337  0.582474  0.790120
3  0.787363  0.587360  0.730951  0.966586  0.603033
4  0.662317  0.504583  0.087809  0.308296  0.034064

##### Sort df wrt index

In [102]:
newdf.sort_index(axis = 0, ascending= False)

            0         1         2         3         4
333  0.598487  0.365627  0.556993  0.077678  0.998507
332  0.571889  0.188152  0.930040  0.352570  0.673688
331  0.902689  0.637977  0.503709  0.264863  0.933552
330  0.244896  0.139392  0.856969  0.287743  0.438733
329  0.942308  0.953576  0.996571  0.518972  0.473479
..        ...       ...       ...       ...       ...
4    0.662317  0.504583  0.087809  0.308296  0.034064
3    0.787363  0.587360  0.730951  0.966586  0.603033
2    0.888869  0.508395  0.946337  0.582474  0.790120
1    0.228106  0.891075  0.052226  0.730936  0.859185
0    0.943622  0.015417  0.697285  0.904292  0.734435

[334 rows x 5 columns]

In [103]:
newdf.sort_index(axis = 0) 
#  AXIS = 0 = COLUMNS = IS VERTICAL DIRECTION - affects rows 
# AND AXIS = 1 ROWS = IS HORIZONTAL DIRECTION - affects columns

            0         1         2         3         4
0    0.943622  0.015417  0.697285  0.904292  0.734435
1    0.228106  0.891075  0.052226  0.730936  0.859185
2    0.888869  0.508395  0.946337  0.582474  0.790120
3    0.787363  0.587360  0.730951  0.966586  0.603033
4    0.662317  0.504583  0.087809  0.308296  0.034064
..        ...       ...       ...       ...       ...
329  0.942308  0.953576  0.996571  0.518972  0.473479
330  0.244896  0.139392  0.856969  0.287743  0.438733
331  0.902689  0.637977  0.503709  0.264863  0.933552
332  0.571889  0.188152  0.930040  0.352570  0.673688
333  0.598487  0.365627  0.556993  0.077678  0.998507

[334 rows x 5 columns]

In [104]:
newdf.sort_index(axis = 1, ascending= False)

            4         3         2         1         0
0    0.734435  0.904292  0.697285  0.015417  0.943622
1    0.859185  0.730936  0.052226  0.891075  0.228106
2    0.790120  0.582474  0.946337  0.508395  0.888869
3    0.603033  0.966586  0.730951  0.587360  0.787363
4    0.034064  0.308296  0.087809  0.504583  0.662317
..        ...       ...       ...       ...       ...
329  0.473479  0.518972  0.996571  0.953576  0.942308
330  0.438733  0.287743  0.856969  0.139392  0.244896
331  0.933552  0.264863  0.503709  0.637977  0.902689
332  0.673688  0.352570  0.930040  0.188152  0.571889
333  0.998507  0.077678  0.556993  0.365627  0.598487

[334 rows x 5 columns]

In [105]:
type(newdf[0])

pandas.Series

In [106]:
newdf.head()

          0         1         2         3         4
0  0.943622  0.015417  0.697285  0.904292  0.734435
1  0.228106  0.891075  0.052226  0.730936  0.859185
2  0.888869  0.508395  0.946337  0.582474  0.790120
3  0.787363  0.587360  0.730951  0.966586  0.603033
4  0.662317  0.504583  0.087809  0.308296  0.034064

### COPY VS VIEW

### COPY CHANGES ONLY THE COPY - ORIGINAL REMAINS THE SAME

In [111]:
newdf2 = newdf.copy() # view is pointing, newdf2 is pointing to newdf.

In [112]:
newdf2.loc[0,0] = 1

In [113]:
newdf2

            0         1         2         3         4
0    1.000000  0.015417  0.697285  0.904292  0.734435
1    0.228106  0.891075  0.052226  0.730936  0.859185
2    0.888869  0.508395  0.946337  0.582474  0.790120
3    0.787363  0.587360  0.730951  0.966586  0.603033
4    0.662317  0.504583  0.087809  0.308296  0.034064
..        ...       ...       ...       ...       ...
329  0.942308  0.953576  0.996571  0.518972  0.473479
330  0.244896  0.139392  0.856969  0.287743  0.438733
331  0.902689  0.637977  0.503709  0.264863  0.933552
332  0.571889  0.188152  0.930040  0.352570  0.673688
333  0.598487  0.365627  0.556993  0.077678  0.998507

[334 rows x 5 columns]

In [114]:
newdf

                0         1         2         3         4
0    74646.000000  0.015417  0.697285  0.904292  0.734435
1        0.228106  0.891075  0.052226  0.730936  0.859185
2        0.888869  0.508395  0.946337  0.582474  0.790120
3        0.787363  0.587360  0.730951  0.966586  0.603033
4        0.662317  0.504583  0.087809  0.308296  0.034064
..            ...       ...       ...       ...       ...
329      0.942308  0.953576  0.996571  0.518972  0.473479
330      0.244896  0.139392  0.856969  0.287743  0.438733
331      0.902689  0.637977  0.503709  0.264863  0.933552
332      0.571889  0.188152  0.930040  0.352570  0.673688
333      0.598487  0.365627  0.556993  0.077678  0.998507

[334 rows x 5 columns]

### VIEW CHANGES BOTH THE ORIGINAL AND THE VIEW DATAFRAME.

In [117]:
newdf2 = newdf
newdf2.loc[0,0] = 23

In [118]:
newdf2

             0         1         2         3         4
0    23.000000  0.015417  0.697285  0.904292  0.734435
1     0.228106  0.891075  0.052226  0.730936  0.859185
2     0.888869  0.508395  0.946337  0.582474  0.790120
3     0.787363  0.587360  0.730951  0.966586  0.603033
4     0.662317  0.504583  0.087809  0.308296  0.034064
..         ...       ...       ...       ...       ...
329   0.942308  0.953576  0.996571  0.518972  0.473479
330   0.244896  0.139392  0.856969  0.287743  0.438733
331   0.902689  0.637977  0.503709  0.264863  0.933552
332   0.571889  0.188152  0.930040  0.352570  0.673688
333   0.598487  0.365627  0.556993  0.077678  0.998507

[334 rows x 5 columns]

In [119]:
newdf

             0         1         2         3         4
0    23.000000  0.015417  0.697285  0.904292  0.734435
1     0.228106  0.891075  0.052226  0.730936  0.859185
2     0.888869  0.508395  0.946337  0.582474  0.790120
3     0.787363  0.587360  0.730951  0.966586  0.603033
4     0.662317  0.504583  0.087809  0.308296  0.034064
..         ...       ...       ...       ...       ...
329   0.942308  0.953576  0.996571  0.518972  0.473479
330   0.244896  0.139392  0.856969  0.287743  0.438733
331   0.902689  0.637977  0.503709  0.264863  0.933552
332   0.571889  0.188152  0.930040  0.352570  0.673688
333   0.598487  0.365627  0.556993  0.077678  0.998507

[334 rows x 5 columns]

In [123]:
newdf.columns = list('abcde')
newdf.head(2)

           a         b         c         d         e
0  23.000000  0.015417  0.697285  0.904292  0.734435
1   0.228106  0.891075  0.052226  0.730936  0.859185

In [130]:
newdf.loc[0,0] = 69
newdf.head(2)

           a         b         c         d         e     0
0  59.000000  0.015417  0.697285  0.904292  0.734435  69.0
1   0.228106  0.891075  0.052226  0.730936  0.859185   NaN

In [129]:
newdf.loc[0,"a"] = 59
newdf.head(2)

           a         b         c         d         e     0
0  59.000000  0.015417  0.697285  0.904292  0.734435  69.0
1   0.228106  0.891075  0.052226  0.730936  0.859185   NaN

#### Delete a column:

In [139]:
newdf = newdf.drop(0, axis = 1)

In [140]:
newdf.head()

           a         b         c         d         e
0  59.000000  0.015417  0.697285  0.904292  0.734435
1   0.228106  0.891075  0.052226  0.730936  0.859185
2   0.888869  0.508395  0.946337  0.582474  0.790120
3   0.787363  0.587360  0.730951  0.966586  0.603033
4   0.662317  0.504583  0.087809  0.308296  0.034064

In [141]:
newdf.loc[[1,2],["c","d"]]

          c         d
1  0.052226  0.730936
2  0.946337  0.582474

In [ ]:
# GET ALL THE ROWS WITH LOC 
newdf.loc[:,["c","d"]]

            c         d
0    0.697285  0.904292
1    0.052226  0.730936
2    0.946337  0.582474
3    0.730951  0.966586
4    0.087809  0.308296
..        ...       ...
329  0.996571  0.518972
330  0.856969  0.287743
331  0.503709  0.264863
332  0.930040  0.352570
333  0.556993  0.077678

[334 rows x 2 columns]

In [145]:
# GET ALL THE COLUMNS WITH LOC
newdf.loc[[1,2],:]

          a         b         c         d         e
1  0.228106  0.891075  0.052226  0.730936  0.859185
2  0.888869  0.508395  0.946337  0.582474  0.790120

In [ ]:
newdf.loc[(newdf["a"]<0.3) & (newdf['c']>0.1)] 
# 'a' COLUMN WHICH IS LESS THAN 0.3 AND 'c' COLUMN WHICH IS GREATER THAN 0.1S

            a         b         c         d         e
17   0.155176  0.352597  0.337626  0.667440  0.288638
22   0.074015  0.966414  0.312433  0.613271  0.078246
25   0.037772  0.230923  0.690127  0.536805  0.677334
28   0.160377  0.273480  0.420659  0.405831  0.764447
31   0.022748  0.198062  0.104397  0.007196  0.781346
..        ...       ...       ...       ...       ...
305  0.186730  0.953268  0.685787  0.564774  0.526339
317  0.200822  0.935006  0.389930  0.732339  0.375761
322  0.297925  0.118363  0.353352  0.601671  0.718927
328  0.179568  0.122733  0.389155  0.277006  0.731407
330  0.244896  0.139392  0.856969  0.287743  0.438733

[96 rows x 5 columns]

> .loc function is used to access the rows or column with the help of index name or column name.

### iloc. FUNCTION:

In [152]:
newdf.head()

           a         b         c         d         e
0  59.000000  0.015417  0.697285  0.904292  0.734435
1   0.228106  0.891075  0.052226  0.730936  0.859185
2   0.888869  0.508395  0.946337  0.582474  0.790120
3   0.787363  0.587360  0.730951  0.966586  0.603033
4   0.662317  0.504583  0.087809  0.308296  0.034064

In [163]:
newdf.iloc[0:3,0:3]

           a         b         c
0  59.000000  0.015417  0.697285
1   0.228106  0.891075  0.052226
2   0.888869  0.508395  0.946337

In [ ]:
newdf.drop(['a','c'],axis = 1)  # no change in original data. change is seen in copy 
newdf # this is OG data

             a         b         c         d         e
0    59.000000  0.015417  0.697285  0.904292  0.734435
1     0.228106  0.891075  0.052226  0.730936  0.859185
2     0.888869  0.508395  0.946337  0.582474  0.790120
3     0.787363  0.587360  0.730951  0.966586  0.603033
4     0.662317  0.504583  0.087809  0.308296  0.034064
..         ...       ...       ...       ...       ...
329   0.942308  0.953576  0.996571  0.518972  0.473479
330   0.244896  0.139392  0.856969  0.287743  0.438733
331   0.902689  0.637977  0.503709  0.264863  0.933552
332   0.571889  0.188152  0.930040  0.352570  0.673688
333   0.598487  0.365627  0.556993  0.077678  0.998507

[334 rows x 5 columns]

In [172]:
newdf.drop(['a','c'],axis = 1, inplace = True) # inplace = True is used to modify the orginial data.

KeyError: "['a', 'c'] not found in axis"

In [ ]:
newdf

            b         d         e
0    0.015417  0.904292  0.734435
1    0.891075  0.730936  0.859185
2    0.508395  0.582474  0.790120
3    0.587360  0.966586  0.603033
4    0.504583  0.308296  0.034064
..        ...       ...       ...
329  0.953576  0.518972  0.473479
330  0.139392  0.287743  0.438733
331  0.637977  0.264863  0.933552
332  0.188152  0.352570  0.673688
333  0.365627  0.077678  0.998507

[334 rows x 3 columns]

In [175]:
newdf.head()

          b         d         e
0  0.015417  0.904292  0.734435
1  0.891075  0.730936  0.859185
2  0.508395  0.582474  0.790120
3  0.587360  0.966586  0.603033
4  0.504583  0.308296  0.034064

In [181]:
newdf.reset_index() # index is reset but another new column is created so we use drop to remove that index.

     index         b         d         e
0        0  0.015417  0.904292  0.734435
1        1  0.891075  0.730936  0.859185
2        2  0.508395  0.582474  0.790120
3        3  0.587360  0.966586  0.603033
4        4  0.504583  0.308296  0.034064
..     ...       ...       ...       ...
329    329  0.953576  0.518972  0.473479
330    330  0.139392  0.287743  0.438733
331    331  0.637977  0.264863  0.933552
332    332  0.188152  0.352570  0.673688
333    333  0.365627  0.077678  0.998507

[334 rows x 4 columns]

In [179]:
newdf.reset_index(drop = True)

            b         d         e
0    0.015417  0.904292  0.734435
1    0.891075  0.730936  0.859185
2    0.508395  0.582474  0.790120
3    0.587360  0.966586  0.603033
4    0.504583  0.308296  0.034064
..        ...       ...       ...
329  0.953576  0.518972  0.473479
330  0.139392  0.287743  0.438733
331  0.637977  0.264863  0.933552
332  0.188152  0.352570  0.673688
333  0.365627  0.077678  0.998507

[334 rows x 3 columns]

In [180]:
newdf.head(2)

          b         d         e
0  0.015417  0.904292  0.734435
1  0.891075  0.730936  0.859185

### REMOVE NULL VALUES

In [184]:
newdf['b'].isnull()

0      False
1      False
2      False
3      False
4      False
       ...
329    False
330    False
331    False
332    False
333    False
Name: b, Length: 334, dtype: bool

In [191]:
newdf.loc[:,['b']] = 56

In [193]:
newdf['b'].isnull().sum()

np.int64(0)

In [202]:
df = pd.DataFrame ({
    "name" :['alfred','batman','alfred'],
    "toy": [np.nan,'batmobile' , 'bullwhip'],
    "born" : [pd.NaT,pd.Timestamp("1940-04-25"),pd.NaT]
}) 
df.head()

     name        toy       born
0  alfred        NaN        NaT
1  batman  batmobile 1940-04-25
2  alfred   bullwhip        NaT

In [203]:
df.dropna(how = "all", axis = 1)

     name        toy       born
0  alfred        NaN        NaT
1  batman  batmobile 1940-04-25
2  alfred   bullwhip        NaT

In [204]:
df.head()

     name        toy       born
0  alfred        NaN        NaT
1  batman  batmobile 1940-04-25
2  alfred   bullwhip        NaT

In [209]:
df.drop_duplicates(subset=['name'], keep = False)

     name        toy       born
1  batman  batmobile 1940-04-25

In [210]:
df.shape

(3, 3)

In [212]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   name    3 non-null      str
 1   toy     2 non-null      str
 2   born    1 non-null      datetime64[us]
dtypes: datetime64[us](1), str(2)
memory usage: 204.0 bytes