### SHREYAN'S AI SKOOL

In [2]:
import pandas as pd
import numpy as np

In [3]:
data = {
    'state': ['Ohio', 'Ohio', 'Ohio', 'Nevada', 'Nevada'],
        'year': [2000, 2001, 2002, 2001, 2002],
        'pop': [1.5, 1.7, 3.6, 2.4, 2.9]
}
data = pd.DataFrame(data) 
data

    state  year  pop
0    Ohio  2000  1.5
1    Ohio  2001  1.7
2    Ohio  2002  3.6
3  Nevada  2001  2.4
4  Nevada  2002  2.9

### SELECTION AND INDEXING OF COLUMNS

In [4]:
data['state']

0      Ohio
1      Ohio
2      Ohio
3    Nevada
4    Nevada
Name: state, dtype: str

In [5]:
data[['state','year']]

    state  year
0    Ohio  2000
1    Ohio  2001
2    Ohio  2002
3  Nevada  2001
4  Nevada  2002

### CREATING A NEW COLUMN

In [8]:
data['designation'] = ['doctor','engineer','police','IAS','athlete']

In [9]:
data

    state  year  pop designation
0    Ohio  2000  1.5      doctor
1    Ohio  2001  1.7    engineer
2    Ohio  2002  3.6      police
3  Nevada  2001  2.4         IAS
4  Nevada  2002  2.9     athlete

### REMOVING A COLUMN

In [11]:
data.drop('designation',axis=1) 
# axis = 1 -> vertical like 1 need to mention to remove a column.

    state  year  pop
0    Ohio  2000  1.5
1    Ohio  2001  1.7
2    Ohio  2002  3.6
3  Nevada  2001  2.4
4  Nevada  2002  2.9

In [12]:
data

    state  year  pop designation
0    Ohio  2000  1.5      doctor
1    Ohio  2001  1.7    engineer
2    Ohio  2002  3.6      police
3  Nevada  2001  2.4         IAS
4  Nevada  2002  2.9     athlete

> only the copy me changes has been occured not in the actual DataFrame.

In [13]:
data.drop('designation',inplace=True, axis=1)

In [14]:
data

    state  year  pop
0    Ohio  2000  1.5
1    Ohio  2001  1.7
2    Ohio  2002  3.6
3  Nevada  2001  2.4
4  Nevada  2002  2.9

In [15]:
data.drop(['state','year'],axis=1)

   pop
0  1.5
1  1.7
2  3.6
3  2.4
4  2.9

In [16]:
data

    state  year  pop
0    Ohio  2000  1.5
1    Ohio  2001  1.7
2    Ohio  2002  3.6
3  Nevada  2001  2.4
4  Nevada  2002  2.9

### SELECTING ROWS

In [17]:
data

    state  year  pop
0    Ohio  2000  1.5
1    Ohio  2001  1.7
2    Ohio  2002  3.6
3  Nevada  2001  2.4
4  Nevada  2002  2.9

In [22]:
data.loc[0]

state    Ohio
year     2000
pop       1.5
Name: 0, dtype: object

In [21]:
data.loc[[0,1]]

  state  year  pop
0  Ohio  2000  1.5
1  Ohio  2001  1.7

In [23]:
data.iloc[3]

state    Nevada
year       2001
pop         2.4
Name: 3, dtype: object

### SELECTING SUBSETS OF ROWS AND COLUMNS

In [24]:
data

    state  year  pop
0    Ohio  2000  1.5
1    Ohio  2001  1.7
2    Ohio  2002  3.6
3  Nevada  2001  2.4
4  Nevada  2002  2.9

In [26]:
data.loc[[0,1]][['year','pop']]

   year  pop
0  2000  1.5
1  2001  1.7

In [28]:
data.loc[[2,3,4]][['state','year']]

    state  year
2    Ohio  2002
3  Nevada  2001
4  Nevada  2002

### CONDITIONAL SELECTION

In [29]:
data

    state  year  pop
0    Ohio  2000  1.5
1    Ohio  2001  1.7
2    Ohio  2002  3.6
3  Nevada  2001  2.4
4  Nevada  2002  2.9