## PHASE 2 OF LEARNING PANDAS

In [2]:
import numpy as np
import pandas as pd

In [3]:
dict1 = {
    "name" : ['harry','rohan','skillf','shubh'],
    "marks" : [93,34,24,17],
    "city" : ['rampur','kolkata','bareilly','antarctica']

}

df = pd.DataFrame(dict1)
print(df)

     name  marks        city
0   harry     93      rampur
1   rohan     34     kolkata
2  skillf     24    bareilly
3   shubh     17  antarctica

#### Transform the dictionary to the csv file.

In [4]:
df.to_csv('friends.csv')

#### Remove the index

In [5]:
df.to_csv('friends_index_false.csv', index = False)

In [6]:
df.head(2)

    name  marks     city
0  harry     93   rampur
1  rohan     34  kolkata

In [7]:
df.tail(2)

     name  marks        city
2  skillf     24    bareilly
3   shubh     17  antarctica

#### Calculate the satistical analysis of numerical column

In [8]:
df.describe()

           marks
count   4.000000
mean   42.000000
std    34.708308
min    17.000000
25%    22.250000
50%    29.000000
75%    48.750000
max    93.000000

#### Change the index

In [9]:
df.index = ['first','second','third','fourth']
df

          name  marks        city
first    harry     93      rampur
second   rohan     34     kolkata
third   skillf     24    bareilly
fourth   shubh     17  antarctica

#### Pandas DataStructure

In [10]:
ser = pd.Series(np.random.rand(34)) 
type(ser)

pandas.Series

In [11]:
newdf = pd.DataFrame(np.random.rand(334,5), index = np.arange(334))
newdf

            0         1         2         3         4
0    0.982537  0.368540  0.781695  0.610650  0.640503
1    0.980295  0.524088  0.102088  0.719481  0.767957
2    0.835169  0.789073  0.673053  0.160443  0.035937
3    0.183016  0.886370  0.999340  0.875175  0.437581
4    0.147253  0.100842  0.879710  0.138585  0.856672
..        ...       ...       ...       ...       ...
329  0.527119  0.150415  0.864526  0.169724  0.076202
330  0.809587  0.639948  0.004576  0.852788  0.464280
331  0.163691  0.754752  0.586696  0.673373  0.253524
332  0.330663  0.534111  0.713155  0.463422  0.718758
333  0.423713  0.684171  0.696280  0.825241  0.427363

[334 rows x 5 columns]

In [12]:
type(newdf)
newdf.head()

          0         1         2         3         4
0  0.982537  0.368540  0.781695  0.610650  0.640503
1  0.980295  0.524088  0.102088  0.719481  0.767957
2  0.835169  0.789073  0.673053  0.160443  0.035937
3  0.183016  0.886370  0.999340  0.875175  0.437581
4  0.147253  0.100842  0.879710  0.138585  0.856672

In [13]:
newdf.describe()

                0           1           2           3           4
count  334.000000  334.000000  334.000000  334.000000  334.000000
mean     0.502946    0.490162    0.523462    0.482298    0.514415
std      0.283417    0.292787    0.290979    0.275676    0.297998
min      0.000236    0.005183    0.001913    0.004023    0.002456
25%      0.252031    0.222585    0.284499    0.248436    0.254895
50%      0.536127    0.486420    0.542345    0.477870    0.519650
75%      0.727214    0.742097    0.779031    0.702008    0.782268
max      0.995427    0.994381    0.999619    0.982761    0.997384

In [14]:
newdf.dtypes

0    float64
1    float64
2    float64
3    float64
4    float64
dtype: object

In [15]:
print(newdf.index)
print("\n")
print(newdf.columns)

Index([  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,
       ...
       324, 325, 326, 327, 328, 329, 330, 331, 332, 333],
      dtype='int64', length=334)


RangeIndex(start=0, stop=5, step=1)

#### Convert my DataFrame to Numpy array

In [16]:
newdf.to_numpy

<bound method DataFrame.to_numpy of             0         1         2         3         4
0    0.982537  0.368540  0.781695  0.610650  0.640503
1    0.980295  0.524088  0.102088  0.719481  0.767957
2    0.835169  0.789073  0.673053  0.160443  0.035937
3    0.183016  0.886370  0.999340  0.875175  0.437581
4    0.147253  0.100842  0.879710  0.138585  0.856672
..        ...       ...       ...       ...       ...
329  0.527119  0.150415  0.864526  0.169724  0.076202
330  0.809587  0.639948  0.004576  0.852788  0.464280
331  0.163691  0.754752  0.586696  0.673373  0.253524
332  0.330663  0.534111  0.713155  0.463422  0.718758
333  0.423713  0.684171  0.696280  0.825241  0.427363

[334 rows x 5 columns]>

In [17]:
newdf.head()

          0         1         2         3         4
0  0.982537  0.368540  0.781695  0.610650  0.640503
1  0.980295  0.524088  0.102088  0.719481  0.767957
2  0.835169  0.789073  0.673053  0.160443  0.035937
3  0.183016  0.886370  0.999340  0.875175  0.437581
4  0.147253  0.100842  0.879710  0.138585  0.856672

#### Learn some attributes

In [18]:
# TRANSPOSE
newdf.T

,0,1,2,3,4,5,6,7,8,9,...,324,325,326,327,328,329,330,331,332,333
0,0.982537,0.980295,0.835169,0.183016,0.147253,0.704054,0.071947,0.874924,0.920740,0.830154,...,0.394022,0.477785,0.622497,0.463265,0.800408,0.527119,0.809587,0.163691,0.330663,0.423713
1,0.368540,0.524088,0.789073,0.886370,0.100842,0.660435,0.852797,0.496976,0.561591,0.121555,...,0.005183,0.078588,0.165129,0.901206,0.873096,0.150415,0.639948,0.754752,0.534111,0.684171
2,0.781695,0.102088,0.673053,0.999340,0.879710,0.888145,0.568258,0.624957,0.454565,0.168732,...,0.304182,0.442123,0.501137,0.408374,0.311026,0.864526,0.004576,0.586696,0.713155,0.696280
3,0.610650,0.719481,0.160443,0.875175,0.138585,0.033904,0.370026,0.239161,0.352419,0.500673,...,0.957459,0.389315,0.522243,0.530801,0.111747,0.169724,0.852788,0.673373,0.463422,0.825241
4,0.640503,0.767957,0.035937,0.437581,0.856672,0.697627,0.366905,0.403475,0.773061,0.981013,...,0.672131,0.429477,0.427569,0.049786,0.842419,0.076202,0.464280,0.253524,0.718758,0.427363

In [19]:
newdf.head()

          0         1         2         3         4
0  0.982537  0.368540  0.781695  0.610650  0.640503
1  0.980295  0.524088  0.102088  0.719481  0.767957
2  0.835169  0.789073  0.673053  0.160443  0.035937
3  0.183016  0.886370  0.999340  0.875175  0.437581
4  0.147253  0.100842  0.879710  0.138585  0.856672

##### Sort df wrt index

In [20]:
newdf.sort_index(axis = 0, ascending= False)

            0         1         2         3         4
333  0.423713  0.684171  0.696280  0.825241  0.427363
332  0.330663  0.534111  0.713155  0.463422  0.718758
331  0.163691  0.754752  0.586696  0.673373  0.253524
330  0.809587  0.639948  0.004576  0.852788  0.464280
329  0.527119  0.150415  0.864526  0.169724  0.076202
..        ...       ...       ...       ...       ...
4    0.147253  0.100842  0.879710  0.138585  0.856672
3    0.183016  0.886370  0.999340  0.875175  0.437581
2    0.835169  0.789073  0.673053  0.160443  0.035937
1    0.980295  0.524088  0.102088  0.719481  0.767957
0    0.982537  0.368540  0.781695  0.610650  0.640503

[334 rows x 5 columns]

In [21]:
newdf.sort_index(axis = 0) 
#  AXIS = 0 = COLUMNS = IS VERTICAL DIRECTION - affects rows 
# AND AXIS = 1 ROWS = IS HORIZONTAL DIRECTION - affects columns

            0         1         2         3         4
0    0.982537  0.368540  0.781695  0.610650  0.640503
1    0.980295  0.524088  0.102088  0.719481  0.767957
2    0.835169  0.789073  0.673053  0.160443  0.035937
3    0.183016  0.886370  0.999340  0.875175  0.437581
4    0.147253  0.100842  0.879710  0.138585  0.856672
..        ...       ...       ...       ...       ...
329  0.527119  0.150415  0.864526  0.169724  0.076202
330  0.809587  0.639948  0.004576  0.852788  0.464280
331  0.163691  0.754752  0.586696  0.673373  0.253524
332  0.330663  0.534111  0.713155  0.463422  0.718758
333  0.423713  0.684171  0.696280  0.825241  0.427363

[334 rows x 5 columns]

In [22]:
newdf.sort_index(axis = 1, ascending= False)

            4         3         2         1         0
0    0.640503  0.610650  0.781695  0.368540  0.982537
1    0.767957  0.719481  0.102088  0.524088  0.980295
2    0.035937  0.160443  0.673053  0.789073  0.835169
3    0.437581  0.875175  0.999340  0.886370  0.183016
4    0.856672  0.138585  0.879710  0.100842  0.147253
..        ...       ...       ...       ...       ...
329  0.076202  0.169724  0.864526  0.150415  0.527119
330  0.464280  0.852788  0.004576  0.639948  0.809587
331  0.253524  0.673373  0.586696  0.754752  0.163691
332  0.718758  0.463422  0.713155  0.534111  0.330663
333  0.427363  0.825241  0.696280  0.684171  0.423713

[334 rows x 5 columns]

In [23]:
type(newdf[0])

pandas.Series

In [24]:
newdf.head()

          0         1         2         3         4
0  0.982537  0.368540  0.781695  0.610650  0.640503
1  0.980295  0.524088  0.102088  0.719481  0.767957
2  0.835169  0.789073  0.673053  0.160443  0.035937
3  0.183016  0.886370  0.999340  0.875175  0.437581
4  0.147253  0.100842  0.879710  0.138585  0.856672

### COPY VS VIEW

### COPY CHANGES ONLY THE COPY - ORIGINAL REMAINS THE SAME

In [25]:
newdf2 = newdf.copy() # view is pointing, newdf2 is pointing to newdf.

In [26]:
newdf2.loc[0,0] = 1

In [27]:
newdf2

            0         1         2         3         4
0    1.000000  0.368540  0.781695  0.610650  0.640503
1    0.980295  0.524088  0.102088  0.719481  0.767957
2    0.835169  0.789073  0.673053  0.160443  0.035937
3    0.183016  0.886370  0.999340  0.875175  0.437581
4    0.147253  0.100842  0.879710  0.138585  0.856672
..        ...       ...       ...       ...       ...
329  0.527119  0.150415  0.864526  0.169724  0.076202
330  0.809587  0.639948  0.004576  0.852788  0.464280
331  0.163691  0.754752  0.586696  0.673373  0.253524
332  0.330663  0.534111  0.713155  0.463422  0.718758
333  0.423713  0.684171  0.696280  0.825241  0.427363

[334 rows x 5 columns]

In [28]:
newdf

            0         1         2         3         4
0    0.982537  0.368540  0.781695  0.610650  0.640503
1    0.980295  0.524088  0.102088  0.719481  0.767957
2    0.835169  0.789073  0.673053  0.160443  0.035937
3    0.183016  0.886370  0.999340  0.875175  0.437581
4    0.147253  0.100842  0.879710  0.138585  0.856672
..        ...       ...       ...       ...       ...
329  0.527119  0.150415  0.864526  0.169724  0.076202
330  0.809587  0.639948  0.004576  0.852788  0.464280
331  0.163691  0.754752  0.586696  0.673373  0.253524
332  0.330663  0.534111  0.713155  0.463422  0.718758
333  0.423713  0.684171  0.696280  0.825241  0.427363

[334 rows x 5 columns]

### VIEW CHANGES BOTH THE ORIGINAL AND THE VIEW DATAFRAME.

In [29]:
newdf2 = newdf
newdf2.loc[0,0] = 23

In [30]:
newdf2

             0         1         2         3         4
0    23.000000  0.368540  0.781695  0.610650  0.640503
1     0.980295  0.524088  0.102088  0.719481  0.767957
2     0.835169  0.789073  0.673053  0.160443  0.035937
3     0.183016  0.886370  0.999340  0.875175  0.437581
4     0.147253  0.100842  0.879710  0.138585  0.856672
..         ...       ...       ...       ...       ...
329   0.527119  0.150415  0.864526  0.169724  0.076202
330   0.809587  0.639948  0.004576  0.852788  0.464280
331   0.163691  0.754752  0.586696  0.673373  0.253524
332   0.330663  0.534111  0.713155  0.463422  0.718758
333   0.423713  0.684171  0.696280  0.825241  0.427363

[334 rows x 5 columns]

In [31]:
newdf

             0         1         2         3         4
0    23.000000  0.368540  0.781695  0.610650  0.640503
1     0.980295  0.524088  0.102088  0.719481  0.767957
2     0.835169  0.789073  0.673053  0.160443  0.035937
3     0.183016  0.886370  0.999340  0.875175  0.437581
4     0.147253  0.100842  0.879710  0.138585  0.856672
..         ...       ...       ...       ...       ...
329   0.527119  0.150415  0.864526  0.169724  0.076202
330   0.809587  0.639948  0.004576  0.852788  0.464280
331   0.163691  0.754752  0.586696  0.673373  0.253524
332   0.330663  0.534111  0.713155  0.463422  0.718758
333   0.423713  0.684171  0.696280  0.825241  0.427363

[334 rows x 5 columns]

In [32]:
newdf.columns = list('abcde')
newdf.head(2)

           a         b         c         d         e
0  23.000000  0.368540  0.781695  0.610650  0.640503
1   0.980295  0.524088  0.102088  0.719481  0.767957

In [33]:
newdf.loc[0,0] = 69
newdf.head(2)

           a         b         c         d         e     0
0  23.000000  0.368540  0.781695  0.610650  0.640503  69.0
1   0.980295  0.524088  0.102088  0.719481  0.767957   NaN

In [34]:
newdf.loc[0,"a"] = 59
newdf.head(2)

           a         b         c         d         e     0
0  59.000000  0.368540  0.781695  0.610650  0.640503  69.0
1   0.980295  0.524088  0.102088  0.719481  0.767957   NaN

#### Delete a column:

In [35]:
newdf = newdf.drop(0, axis = 1)

In [36]:
newdf.head()

           a         b         c         d         e
0  59.000000  0.368540  0.781695  0.610650  0.640503
1   0.980295  0.524088  0.102088  0.719481  0.767957
2   0.835169  0.789073  0.673053  0.160443  0.035937
3   0.183016  0.886370  0.999340  0.875175  0.437581
4   0.147253  0.100842  0.879710  0.138585  0.856672

In [37]:
newdf.loc[[1,2],["c","d"]]

          c         d
1  0.102088  0.719481
2  0.673053  0.160443

In [38]:
# GET ALL THE ROWS WITH LOC 
newdf.loc[:,["c","d"]]

            c         d
0    0.781695  0.610650
1    0.102088  0.719481
2    0.673053  0.160443
3    0.999340  0.875175
4    0.879710  0.138585
..        ...       ...
329  0.864526  0.169724
330  0.004576  0.852788
331  0.586696  0.673373
332  0.713155  0.463422
333  0.696280  0.825241

[334 rows x 2 columns]

In [39]:
# GET ALL THE COLUMNS WITH LOC
newdf.loc[[1,2],:]

          a         b         c         d         e
1  0.980295  0.524088  0.102088  0.719481  0.767957
2  0.835169  0.789073  0.673053  0.160443  0.035937

In [40]:
newdf.loc[(newdf["a"]<0.3) & (newdf['c']>0.1)] 
# 'a' COLUMN WHICH IS LESS THAN 0.3 AND 'c' COLUMN WHICH IS GREATER THAN 0.1S

            a         b         c         d         e
3    0.183016  0.886370  0.999340  0.875175  0.437581
4    0.147253  0.100842  0.879710  0.138585  0.856672
6    0.071947  0.852797  0.568258  0.370026  0.366905
14   0.171554  0.427125  0.600747  0.113055  0.800111
15   0.229572  0.858137  0.798588  0.448971  0.788051
..        ...       ...       ...       ...       ...
314  0.087760  0.770486  0.522822  0.172838  0.858439
315  0.000236  0.679622  0.494391  0.243219  0.365561
316  0.133148  0.006049  0.112394  0.449192  0.211150
322  0.255305  0.799959  0.390332  0.456596  0.655168
331  0.163691  0.754752  0.586696  0.673373  0.253524

[93 rows x 5 columns]

> .loc function is used to access the rows or column with the help of index name or column name.

### iloc. FUNCTION:

In [41]:
newdf.head()

           a         b         c         d         e
0  59.000000  0.368540  0.781695  0.610650  0.640503
1   0.980295  0.524088  0.102088  0.719481  0.767957
2   0.835169  0.789073  0.673053  0.160443  0.035937
3   0.183016  0.886370  0.999340  0.875175  0.437581
4   0.147253  0.100842  0.879710  0.138585  0.856672

In [42]:
newdf.iloc[0:3,0:3]

           a         b         c
0  59.000000  0.368540  0.781695
1   0.980295  0.524088  0.102088
2   0.835169  0.789073  0.673053

In [43]:
newdf.drop(['a','c'],axis = 1)  # no change in original data. change is seen in copy 
newdf # this is OG data

             a         b         c         d         e
0    59.000000  0.368540  0.781695  0.610650  0.640503
1     0.980295  0.524088  0.102088  0.719481  0.767957
2     0.835169  0.789073  0.673053  0.160443  0.035937
3     0.183016  0.886370  0.999340  0.875175  0.437581
4     0.147253  0.100842  0.879710  0.138585  0.856672
..         ...       ...       ...       ...       ...
329   0.527119  0.150415  0.864526  0.169724  0.076202
330   0.809587  0.639948  0.004576  0.852788  0.464280
331   0.163691  0.754752  0.586696  0.673373  0.253524
332   0.330663  0.534111  0.713155  0.463422  0.718758
333   0.423713  0.684171  0.696280  0.825241  0.427363

[334 rows x 5 columns]

In [44]:
newdf.drop(['a','c'],axis = 1, inplace = True) # inplace = True is used to modify the orginial data.

In [45]:
newdf

            b         d         e
0    0.368540  0.610650  0.640503
1    0.524088  0.719481  0.767957
2    0.789073  0.160443  0.035937
3    0.886370  0.875175  0.437581
4    0.100842  0.138585  0.856672
..        ...       ...       ...
329  0.150415  0.169724  0.076202
330  0.639948  0.852788  0.464280
331  0.754752  0.673373  0.253524
332  0.534111  0.463422  0.718758
333  0.684171  0.825241  0.427363

[334 rows x 3 columns]

In [46]:
newdf.head()

          b         d         e
0  0.368540  0.610650  0.640503
1  0.524088  0.719481  0.767957
2  0.789073  0.160443  0.035937
3  0.886370  0.875175  0.437581
4  0.100842  0.138585  0.856672

In [47]:
newdf.reset_index() # index is reset but another new column is created so we use drop to remove that index.

     index         b         d         e
0        0  0.368540  0.610650  0.640503
1        1  0.524088  0.719481  0.767957
2        2  0.789073  0.160443  0.035937
3        3  0.886370  0.875175  0.437581
4        4  0.100842  0.138585  0.856672
..     ...       ...       ...       ...
329    329  0.150415  0.169724  0.076202
330    330  0.639948  0.852788  0.464280
331    331  0.754752  0.673373  0.253524
332    332  0.534111  0.463422  0.718758
333    333  0.684171  0.825241  0.427363

[334 rows x 4 columns]

In [48]:
newdf.reset_index(drop = True)

            b         d         e
0    0.368540  0.610650  0.640503
1    0.524088  0.719481  0.767957
2    0.789073  0.160443  0.035937
3    0.886370  0.875175  0.437581
4    0.100842  0.138585  0.856672
..        ...       ...       ...
329  0.150415  0.169724  0.076202
330  0.639948  0.852788  0.464280
331  0.754752  0.673373  0.253524
332  0.534111  0.463422  0.718758
333  0.684171  0.825241  0.427363

[334 rows x 3 columns]

In [49]:
newdf.head(2)

          b         d         e
0  0.368540  0.610650  0.640503
1  0.524088  0.719481  0.767957

### REMOVE NULL VALUES

In [50]:
newdf['b'].isnull()

0      False
1      False
2      False
3      False
4      False
       ...
329    False
330    False
331    False
332    False
333    False
Name: b, Length: 334, dtype: bool

In [51]:
newdf.loc[:,['b']] = 56

In [52]:
newdf['b'].isnull().sum()

np.int64(0)

In [53]:
df = pd.DataFrame ({
    "name" :['alfred','batman','alfred'],
    "toy": [np.nan,'batmobile' , 'bullwhip'],
    "born" : [pd.NaT,pd.Timestamp("1940-04-25"),pd.NaT]
}) 
df.head()

     name        toy       born
0  alfred        NaN        NaT
1  batman  batmobile 1940-04-25
2  alfred   bullwhip        NaT

In [54]:
df.dropna(how = "all", axis = 1)

     name        toy       born
0  alfred        NaN        NaT
1  batman  batmobile 1940-04-25
2  alfred   bullwhip        NaT

In [55]:
df.head()

     name        toy       born
0  alfred        NaN        NaT
1  batman  batmobile 1940-04-25
2  alfred   bullwhip        NaT

In [62]:
df.drop_duplicates(subset=['name'], keep = False)

     name        toy       born
1  batman  batmobile 1940-04-25

In [63]:
df

     name        toy       born
0  alfred        NaN        NaT
1  batman  batmobile 1940-04-25
2  alfred   bullwhip        NaT

In [67]:
df.shape

(3, 3)

In [70]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   name    3 non-null      str
 1   toy     2 non-null      str
 2   born    1 non-null      datetime64[us]
dtypes: datetime64[us](1), str(2)
memory usage: 204.0 bytes

In [77]:
df['name'].value_counts(dropna= False) # dropna = False mtlb ki na ko mat gino
df['name'].value_counts(dropna= True) # dropna = False mtlb ki na ko mat gino

name
alfred    2
batman    1
Name: count, dtype: int64

In [78]:
df.notnull()

   name    toy   born
0  True  False  False
1  True   True   True
2  True   True  False

In [79]:
df.isnull()

    name    toy   born
0  False   True   True
1  False  False  False
2  False  False   True