# ANIME PROJECT

In [2]:
import pandas as pd
import numpy as np

In [3]:
df = pd.read_csv(r"C:\Abhishree\Projects_GitHubLinked\datasets\ANIME\anime.csv")

In [4]:
df.head()

   Rank                                              Title  Score
0     1  Fullmetal Alchemist: BrotherhoodTV (64 eps)Apr...   9.10
1     2  Steins;GateTV (24 eps)Apr 2011 - Sep 20112,473...   9.07
2     3  Bleach: Sennen Kessen-henTV (13 eps)Oct 2022 -...   9.06
3     4  Gintama°TV (51 eps)Apr 2015 - Mar 2016605,113 ...   9.06
4     5  Shingeki no Kyojin Season 3 Part 2TV (10 eps)A...   9.05

In [5]:
df.columns

Index(['Rank', 'Title', 'Score'], dtype='str')

In [6]:
df.index

RangeIndex(start=0, stop=50, step=1)

> make a new column for episode count.

In [7]:
df.loc[2]['Title']

'Bleach: Sennen Kessen-henTV (13 eps)Oct 2022 - Dec 2022474,138 members'

episode given so we extract this - feature extraction

In [8]:
def extract_episode(txt):
    check = False
    data = ""
    for i in txt:
        if i == ')':
            check = False
            return data
        if check == True:
            data += i
        if i == '(':
            check = True

In [9]:
df['episodes'] = df['Title'].apply(extract_episode)

In [10]:
df.head()

   Rank                                              Title  Score episodes
0     1  Fullmetal Alchemist: BrotherhoodTV (64 eps)Apr...   9.10   64 eps
1     2  Steins;GateTV (24 eps)Apr 2011 - Sep 20112,473...   9.07   24 eps
2     3  Bleach: Sennen Kessen-henTV (13 eps)Oct 2022 -...   9.06   13 eps
3     4  Gintama°TV (51 eps)Apr 2015 - Mar 2016605,113 ...   9.06   51 eps
4     5  Shingeki no Kyojin Season 3 Part 2TV (10 eps)A...   9.05   10 eps

In [11]:
df['episodes'] = df['episodes'].str.replace(' eps','')

In [12]:
df['episodes'].astype(int)

0      64
1      24
2      13
3      51
4      10
5      51
6       1
7     148
8      13
9      13
10      2
11    110
12     13
13     13
14     12
15    201
16      1
17     22
18     24
19     25
20      1
21      1
22      7
23     14
24     74
25      1
26      1
27     12
28      1
29     24
30     23
31     12
32     26
33     13
34     16
35     11
36      1
37     11
38     10
39      1
40     26
41     12
42     75
43     26
44     26
45     24
46     10
47     12
48     12
49      4
Name: episodes, dtype: int64

In [13]:
df

    Rank                                              Title  Score episodes
0      1  Fullmetal Alchemist: BrotherhoodTV (64 eps)Apr...   9.10       64
1      2  Steins;GateTV (24 eps)Apr 2011 - Sep 20112,473...   9.07       24
2      3  Bleach: Sennen Kessen-henTV (13 eps)Oct 2022 -...   9.06       13
3      4  Gintama°TV (51 eps)Apr 2015 - Mar 2016605,113 ...   9.06       51
4      5  Shingeki no Kyojin Season 3 Part 2TV (10 eps)A...   9.05       10
5      6  Gintama'TV (51 eps)Apr 2011 - Mar 2012534,105 ...   9.04       51
6      7  Gintama: The FinalMovie (1 eps)Jan 2021 - Jan ...   9.04        1
7      8  Hunter x Hunter TV (148 eps)Oct 2011 - Sep 201...   9.04      148
8      9  Kaguya-sama wa Kokurasetai: Ultra RomanticTV (...   9.04       13
9     10  Gintama': EnchousenTV (13 eps)Oct 2012 - Mar 2...   9.03       13
10    11  Shingeki no Kyojin: The Final Season - Kankets...   9.03        2
11    12  Ginga Eiyuu DensetsuOVA (110 eps)Jan 1988 - Ma...   9.02      110
12    13  Bleach: Sennen Kessen-hen - Ketsubetsu-tanTV (...   8.99       13
13    14  Fruits Basket: The FinalTV (13 eps)Apr 2021 - ...   8.99       13
14    15  Gintama.TV (12 eps)Jan 2017 - Mar 2017302,232 ...   8.98       12
15    16  GintamaTV (201 eps)Apr 2006 - Mar 20101,034,41...   8.94      201
16    17  Koe no KatachiMovie (1 eps)Sep 2016 - Sep 2016...   8.94        1
17    18  3-gatsu no Lion 2nd SeasonTV (22 eps)Oct 2017 ...   8.93       22
18    19  Clannad: After StoryTV (24 eps)Oct 2008 - Mar ...   8.93       24
19    20  Code Geass: Hangyaku no Lelouch R2TV (25 eps)A...   8.91       25
20    21  Gintama Movie 2: Kanketsu-hen - Yorozuya yo Ei...   8.91        1
21    22  Violet Evergarden MovieMovie (1 eps)Sep 2020 -...   8.89        1
22    23  Owarimonogatari 2nd SeasonTV (7 eps)Aug 2017 -...   8.88        7
23    24  Gintama.: Shirogane no Tamashii-hen - Kouhan-s...   8.88       14
24    25  MonsterTV (74 eps)Apr 2004 - Sep 20051,041,081...   8.87       74
25    26  Kimi no Na wa.Movie (1 eps)Aug 2016 - Aug 2016...   8.84        1
26    27  Kaguya-sama wa Kokurasetai: First Kiss wa Owar...   8.84        1
27    28  Bocchi the Rock!TV (12 eps)Oct 2022 - Dec 2022...   8.83       12
28    29  The First Slam DunkMovie (1 eps)Dec 2022 - Dec...   8.83        1
29    30  Vinland Saga Season 2TV (24 eps)Jan 2023 - Jun...   8.82       24
30    31  Jujutsu Kaisen 2nd SeasonTV (23 eps)Jul 2023 -...   8.82       23
31    32  Gintama.: Shirogane no Tamashii-henTV (12 eps)...   8.81       12
32    33  Kingdom 3rd SeasonTV (26 eps)Apr 2020 - Oct 20...   8.81       26
33    34  Mob Psycho 100 IITV (13 eps)Jan 2019 - Apr 201...   8.80       13
34    35  Shingeki no Kyojin: The Final SeasonTV (16 eps...   8.80       16
35    36  Kimetsu no Yaiba: Yuukaku-henTV (11 eps)Dec 20...   8.79       11
36    37  Kizumonogatari III: Reiketsu-henMovie (1 eps)J...   8.79        1
37    38  "Oshi no Ko"TV (11 eps)Apr 2023 - Jun 2023645,...   8.79       11
38    39  Haikyuu!! Karasuno Koukou vs. Shiratorizawa Ga...   8.78       10
39    40  Sen to Chihiro no KamikakushiMovie (1 eps)Jul ...   8.78        1
40    41  Monogatari Series: Second SeasonTV (26 eps)Jul...   8.77       26
41    42  Shingeki no Kyojin: The Final Season Part 2TV ...   8.77       12
42    43  Hajime no IppoTV (75 eps)Oct 2000 - Mar 200255...   8.76       75
43    44  Cowboy BebopTV (26 eps)Apr 1998 - Apr 19991,79...   8.75       26
44    45  Kingdom 4th SeasonTV (26 eps)Apr 2022 - Oct 20...   8.75       26
45    46  Vinland SagaTV (24 eps)Jul 2019 - Dec 20191,40...   8.74       24
46    47  Mushishi Zoku Shou 2nd SeasonTV (10 eps)Oct 20...   8.73       10
47    48  Shouwa Genroku Rakugo Shinjuu: Sukeroku Futata...   8.72       12
48    49  Mob Psycho 100 IIITV (12 eps)Oct 2022 - Dec 20...   8.71       12
49    50  Rurouni Kenshin: Meiji Kenkaku Romantan - Tsui...   8.71        4

> Make a new column for time stamp

In [14]:
df.head()

   Rank                                              Title  Score episodes
0     1  Fullmetal Alchemist: BrotherhoodTV (64 eps)Apr...   9.10       64
1     2  Steins;GateTV (24 eps)Apr 2011 - Sep 20112,473...   9.07       24
2     3  Bleach: Sennen Kessen-henTV (13 eps)Oct 2022 -...   9.06       13
3     4  Gintama°TV (51 eps)Apr 2015 - Mar 2016605,113 ...   9.06       51
4     5  Shingeki no Kyojin Season 3 Part 2TV (10 eps)A...   9.05       10

In [15]:
df.loc[2]['Title']

'Bleach: Sennen Kessen-henTV (13 eps)Oct 2022 - Dec 2022474,138 members'

In [16]:
def extract_time(txt):
    check = False
    data = ""
    for i in range(len(txt)):
        if txt[i] == ')': 
            for j in range(i+1,i+20):
                data += txt[j]
            return data

In [17]:
df['Total Time'] = df['Title'].apply(extract_time)

In [18]:
df.head()

,Rank,Title,Score,episodes,Total Time
0,1,Fullmetal Alchemist: BrotherhoodTV (64 eps)Apr...,9.10,64,Apr 2009 - Jul 2010
1,2,"Steins;GateTV (24 eps)Apr 2011 - Sep 20112,473...",9.07,24,Apr 2011 - Sep 2011
2,3,Bleach: Sennen Kessen-henTV (13 eps)Oct 2022 -...,9.06,13,Oct 2022 - Dec 2022
3,4,"Gintama°TV (51 eps)Apr 2015 - Mar 2016605,113 ...",9.06,51,Apr 2015 - Mar 2016
4,5,Shingeki no Kyojin Season 3 Part 2TV (10 eps)A...,9.05,10,Apr 2019 - Jul 2019

Extracting months from Total Time attribute.

In [19]:
df.head()

,Rank,Title,Score,episodes,Total Time
0,1,Fullmetal Alchemist: BrotherhoodTV (64 eps)Apr...,9.10,64,Apr 2009 - Jul 2010
1,2,"Steins;GateTV (24 eps)Apr 2011 - Sep 20112,473...",9.07,24,Apr 2011 - Sep 2011
2,3,Bleach: Sennen Kessen-henTV (13 eps)Oct 2022 -...,9.06,13,Oct 2022 - Dec 2022
3,4,"Gintama°TV (51 eps)Apr 2015 - Mar 2016605,113 ...",9.06,51,Apr 2015 - Mar 2016
4,5,Shingeki no Kyojin Season 3 Part 2TV (10 eps)A...,9.05,10,Apr 2019 - Jul 2019

In [20]:
import pandas as pd

# 1. Split the 'Total Time' column into 'Start' and 'End' parts
dates = df['Total Time'].str.split(' - ', expand=True)

# 2. Convert both parts into proper datetime format
start_date = pd.to_datetime(dates[0], format='%b %Y')
end_date = pd.to_datetime(dates[1], format='%b %Y')

# 3. Calculate the difference in months
# (Years difference * 12) + Months difference + 1 (to include the starting month)
df['Months'] = (end_date.dt.year - start_date.dt.year) * 12 + (end_date.dt.month - start_date.dt.month) + 1

# View the result
print(df[['Total Time', 'Months']].head())

            Total Time  Months
0  Apr 2009 - Jul 2010      16
1  Apr 2011 - Sep 2011       6
2  Oct 2022 - Dec 2022       3
3  Apr 2015 - Mar 2016      12
4  Apr 2019 - Jul 2019       4

In [21]:
df.head(3)

,Rank,Title,Score,episodes,Total Time,Months
0,1,Fullmetal Alchemist: BrotherhoodTV (64 eps)Apr...,9.10,64,Apr 2009 - Jul 2010,16
1,2,"Steins;GateTV (24 eps)Apr 2011 - Sep 20112,473...",9.07,24,Apr 2011 - Sep 2011,6
2,3,Bleach: Sennen Kessen-henTV (13 eps)Oct 2022 -...,9.06,13,Oct 2022 - Dec 2022,3

> which anime has the highest score?

In [22]:
df[df['Score'] == df['Score'].max()]

,Rank,Title,Score,episodes,Total Time,Months
0,1,Fullmetal Alchemist: BrotherhoodTV (64 eps)Apr...,9.1,64,Apr 2009 - Jul 2010,16

> give me top 5 highest scoring anime

In [32]:
df['Title'].head()

0    Fullmetal Alchemist: BrotherhoodTV (64 eps)Apr...
1    Steins;GateTV (24 eps)Apr 2011 - Sep 20112,473...
2    Bleach: Sennen Kessen-henTV (13 eps)Oct 2022 -...
3    Gintama°TV (51 eps)Apr 2015 - Mar 2016605,113 ...
4    Shingeki no Kyojin Season 3 Part 2TV (10 eps)A...
Name: Title, dtype: str

>  which anime has the highest episode count?

In [41]:
df[df['episodes'] == df['episodes'].max()]

,Rank,Title,Score,episodes,Total Time,Months
42,43,Hajime no IppoTV (75 eps)Oct 2000 - Mar 200255...,8.76,75,Oct 2000 - Mar 2002,18

In [42]:
df.loc[df['episodes'].idxmax(), 'Title']

'Hajime no IppoTV (75 eps)Oct 2000 - Mar 2002558,435 members'

> anime with top 5 episode count

In [43]:
df.head(3)

,Rank,Title,Score,episodes,Total Time,Months
0,1,Fullmetal Alchemist: BrotherhoodTV (64 eps)Apr...,9.10,64,Apr 2009 - Jul 2010,16
1,2,"Steins;GateTV (24 eps)Apr 2011 - Sep 20112,473...",9.07,24,Apr 2011 - Sep 2011,6
2,3,Bleach: Sennen Kessen-henTV (13 eps)Oct 2022 -...,9.06,13,Oct 2022 - Dec 2022,3

In [52]:
df.sort_values(by='episodes', ascending=False).head()['Title']

42    Hajime no IppoTV (75 eps)Oct 2000 - Mar 200255...
24    MonsterTV (74 eps)Apr 2004 - Sep 20051,041,081...
22    Owarimonogatari 2nd SeasonTV (7 eps)Aug 2017 -...
0     Fullmetal Alchemist: BrotherhoodTV (64 eps)Apr...
3     Gintama°TV (51 eps)Apr 2015 - Mar 2016605,113 ...
Name: Title, dtype: str

> which is the largest running anime.

In [53]:
df.head(3)

,Rank,Title,Score,episodes,Total Time,Months
0,1,Fullmetal Alchemist: BrotherhoodTV (64 eps)Apr...,9.10,64,Apr 2009 - Jul 2010,16
1,2,"Steins;GateTV (24 eps)Apr 2011 - Sep 20112,473...",9.07,24,Apr 2011 - Sep 2011,6
2,3,Bleach: Sennen Kessen-henTV (13 eps)Oct 2022 -...,9.06,13,Oct 2022 - Dec 2022,3

In [58]:
df[df['Months'] == df['Months'].max()]['Title']

11    Ginga Eiyuu DensetsuOVA (110 eps)Jan 1988 - Ma...
Name: Title, dtype: str

In [59]:
df[df['Months'] == df['Months'].max()]

,Rank,Title,Score,episodes,Total Time,Months
11,12,Ginga Eiyuu DensetsuOVA (110 eps)Jan 1988 - Ma...,9.02,110,Jan 1988 - Mar 1997,111